Add more POSIX shell compatibility.
conda-forge/openmpi-feedstock pull request #163
Opened 2024-06-13 03:50 UTC by ktlim

`${!}` indirection is also a bash-only feature.
Also set `OMPI_FCFLAGS` once.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-06-13 03:50 UTC, ktlim commented
@conda-forge-admin, please rerender

2024-06-13 06:48 UTC, minrk commented
Thanks for the PR! let's please solve this in #159 instead of separately. Instead of merging this, I'll fix it in #159 to avoid introducing more conflicts.

Can I ask how you encountered this? I've been testing with at least zsh, bash, and sh, all of which don't have an issue. conda-build specifies that build scripts are run in bash, so the `if $CONDA_BUILD` part should only. But maybe some shells do processing of the whole file differently.

2024-06-13 06:51 UTC, minrk requested changes
will be applied in #159

2024-06-13 19:45 UTC, closed without merging

2024-06-13 21:17 UTC, ktlim commented
We only encountered the problem with the first line (which was why that was the only fix at first) trying to activate `openmpi` on Debian under `/bin/sh` (which is not `bash`).  I thought I had looked around for documentation on conda-build's shell but now I see that it is indeed specified to be bash, so this PR wasn't really necessary.

2024-06-13 21:19 UTC, beckermr commented
I guess it depends on how much of the file the shell interprets. If it goes line by line, then we could have not-supported syntax tucked in an if statement and it'd be fine. IDK how the shell actually does things.

2024-06-14 07:49 UTC, minrk commented
@ktlim thanks! That's my understanding, and thanks for the fix in #162. We can come back with more fixes if someone encounters a problem, but at least for now I think we can say that this is `sh`-compatible, and I've tested that it works with `/bin/sh` for me, at least.

2025-09-22 22:00 UTC, timj commented
It looks like the ticket that closed this made things worse and I see that the fixes from #162 got reverted last month so the script errors out all the time.

```
#42 482.4 ./lsstinstall: 3: /opt/lsst/software/stack/conda/envs/lsst-scipipe-11.0.0/etc/conda/activate.d/openmpi_activate.sh: [[: not found
#42 482.4 ./lsstinstall: 3: /opt/lsst/software/stack/conda/envs/lsst-scipipe-11.0.0/etc/conda/activate.d/openmpi_activate.sh: -n: not found
```

Something is seemingly wrong in terms of whether these .sh have to be posix or not.